# Create new user 
- hosts: dharmapublic
  tasks:
          - name: "create users nginx"
            user:
                    name: public
                    password: "$6$7FpOHcrYkSX$8hUe1sL.aZW5Z4LxKATr3wyY.meyAxt//8ZF6PMsF0VfeIjZYorWAk2gYp5q2sUoFo2kj6qIObvA01Q2dzo19."
                    groups: sudo,docker
                    state: present
                    shell: /bin/bash
                    system: no
                    createhome: yes
                    home: /home/public

- hosts: dharmadb
  tasks:
          - name: "create users database"
            user:
                    name: db
                    password: "$6$7FpOHcrYkSX$8hUe1sL.aZW5Z4LxKATr3wyY.meyAxt//8ZF6PMsF0VfeIjZYorWAk2gYp5q2sUoFo2kj6qIObvA01Q2dzo19."
                    groups: sudo,docker
                    state: present
                    shell: /bin/bash
                    system: no
                    createhome: yes
                    home: /home/db

- hosts: dharmabackend
  tasks:
          - name: "create users backend"
            user:
                    name: be
                    password: "$6$7FpOHcrYkSX$8hUe1sL.aZW5Z4LxKATr3wyY.meyAxt//8ZF6PMsF0VfeIjZYorWAk2gYp5q2sUoFo2kj6qIObvA01Q2dzo19."
                    groups: sudo,docker
                    state: present
                    shell: /bin/bash
                    system: no
                    createhome: yes
                    home: /home/be


- hosts: dharmaprivate
  tasks:
          - name: "create users frontend1"
            user:
                    name: fe1
                    password: "$6$7FpOHcrYkSX$8hUe1sL.aZW5Z4LxKATr3wyY.meyAxt//8ZF6PMsF0VfeIjZYorWAk2gYp5q2sUoFo2kj6qIObvA01Q2dzo19."
                    groups: sudo,docker
                    state: present
                    shell: /bin/bash
                    system: no
                    createhome: yes
                    home: /home/fe1

- hosts: dharmafrontend
  tasks:
          - name: "create users frontend2"
            user:
                    name: fe2
                    password: "$6$7FpOHcrYkSX$8hUe1sL.aZW5Z4LxKATr3wyY.meyAxt//8ZF6PMsF0VfeIjZYorWAk2gYp5q2sUoFo2kj6qIObvA01Q2dzo19."
                    groups: sudo,docker
                    state: present
                    shell: /bin/bash
                    system: no
                    createhome: yes
                    home: /home/fe2

- hosts: dharmacicd
  tasks:
          - name: "create users jenkins"
            user:
                    name: jk
                    password: "$6$7FpOHcrYkSX$8hUe1sL.aZW5Z4LxKATr3wyY.meyAxt//8ZF6PMsF0VfeIjZYorWAk2gYp5q2sUoFo2kj6qIObvA01Q2dzo19."
                    groups: sudo,docker
                    state: present
                    shell: /bin/bash
                    system: no
                    createhome: yes
                    home: /home/jk
                    
- hosts: dharmamonitoring
  tasks:
          - name: "create users monitoring"
            user:
                    name: ps
                    password: "$6$7FpOHcrYkSX$8hUe1sL.aZW5Z4LxKATr3wyY.meyAxt//8ZF6PMsF0VfeIjZYorWAk2gYp5q2sUoFo2kj6qIObvA01Q2dzo19."
                    groups: sudo,docker
                    state: present
                    shell: /bin/bash
                    system: no
                    createhome: yes
                    home: /home/ps
                    
# Change PasswordAuthentication and rload sshd
- hosts: all
  tasks:
          - name: change PasswordAuth
            lineinfile:
                    path: /etc/ssh/sshd_config
                    regexp: 'PasswordAuthentication no'
                    line: PasswordAuthentication yes

          - name: reload sshd
            systemd:
                    name: sshd
                    state: reloaded
