- hosts: be:fe
  tasks:
          - debug:
              msg: "{{ansible_user}}"
          - name: generate SSH key "{{ssh_name}}"
            user:
                 name: "{{ansible_user}}"
                 generate_ssh_key: yes
                 ssh_key_type: rsa
                 ssh_key_bits: 4096
                 ssh_key_file: .ssh/{{ssh_name}}
                 force: no
