- hosts: be
  tasks:
          - name: git clone
            git:
                    repo: git@github.com:igstbagusdharmaputra/housy-be.git
                    version: production
                    dest: "/home/{{ansible_user}}/housy-be/"
                    accept_hostkey: yes
            become_user: "{{ansible_user}}"
                    
- hosts: fe 
  tasks:
          - name: git clone
            git:
                    repo: git@github.com:igstbagusdharmaputra/housy-fe.git
                    version: production
                    dest: "/home/{{ansible_user}}/housy-fe/"
                    accept_hostkey: yes
            become_user: "{{ansible_user}}"
