- hosts: dharmabackend
  tasks:
          - name: git clone
            git:
                    repo: git@github.com:igstbagusdharmaputra/backend-private.git
                    version: main
                    dest: "/home/{{ansible_user}}/housy-be/"
                    accept_hostkey: yes
            become_user: "{{ansible_user}}"
                    
- hosts: dharmaprivate:dharmafrontend 
  tasks:
          - name: git clone
            git:
                    repo: git@github.com:igstbagusdharmaputra/frontend-private.git
                    version: main
                    dest: ~/housy-fe/
                    accept_hostkey: yes
            become_user: "{{ansible_user}}"
