- hosts: all
  tasks:
          - name: "create universal users"
            user:
                    name: devops
                    password: "$6$3GUF56qm$Mv2FxgYm0WtLUNyHOOafe/diWKCQegmy5uqFjcT4tBo0in9FJx/BQwFTSll4U59rnw8puX4dC3UYpL9muS.0R1"
                    groups: sudo,docker
                    state: present
                    shell: /bin/bash
                    system: yes
                    home: /home/devops
