- hosts: mn
  tasks:
    - name: mkdir docker
      file:
        path: /home/devops/prometheus
        state: directory

    - name: copy prometheus conf
      copy:
        src: ../files/prometheus.yml
        dest: /home/devops/prometheus/prometheus.yml

    - name: mkdir grafana
      file:
        path: /home/devops/grafana
        mode: 0777
        owner: root
        group: root
        state: directory

    - name: run prometheus
      docker_container:
        name: prometheus
        image: prom/prometheus
        volumes:
             - "/home/devops/prometheus:/etc/prometheus"
        ports:
             - "9090:9090"
        detach: yes
        state: started

    - name: run grafana
      docker_container:
        name: grafana
        image: grafana/grafana
        ports:
             - "3000:3000"
        detach: yes
        volumes:
             - "/home/devops/grafana:/var/lib/grafana"
             - "/home/devops/grafana/grafana.ini:/etc/grafana/grafana.ini"
        state: started
