- hosts: mn
  tasks:
          - name: grafana
            docker_container:
                name: grafana
                state: started
          - name: prometheus
            docker_container:
                 name: prometheus
                 state: started
