- hosts: cicd
  tasks:
    - name: Run Jenkins container
      docker_container:
        name: cicd
        image: jenkins/jenkins:lts
        state: started
        ports: 
           - "8080:8080"
           - "50000:50000"
        volumes:
           - "jenkins_homecicd:/usr/app"
           #- /var/run/docker.sock:/var/run/doc1ker.sock
