- hosts: fe
  tasks:  
     - name: compose up fe
       shell:
          cmd: "docker-compose down"
          chdir: "/home/{{ansible_user}}/housy-fe"    
- hosts: be
  tasks:
     - name: be
       shell:
          cmd: "docker-compose down"
          chdir: "/home/{{ansible_user}}/housy-be"


