- hosts: fe
  tasks:  
     - name: compose up fe
       shell:
          cmd: "docker-compose up -d"
          chdir: "/home/{{ansible_user}}/housy-fe"    
- hosts: be
  tasks:
     - name: compose up be  
       shell:
          cmd: "docker-compose up -d"
          chdir: "/home/{{ansible_user}}/housy-be"


