- hosts: fe
  tasks:
          - name: frontend
            docker_container:
                name: fe
                state: absent
          - name: frontend1
            docker_container:
                name: fe1
                state: absent

- hosts: be
  tasks:
          - name: backend
            docker_container:
                name: be
                state: absent
